# Pytis translations 
# Copyright (C) 2008-2011 OUI Technology Ltd. 
# This file is distributed under the same license as the Pytis package. 
#
msgid ""
msgstr ""
"Project-Id-Version: 0.1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2020-01-29 22:40+0100\n"
"PO-Revision-Date: 2011-12-29 14:56+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Hungarian <wiking@lists.freebsoft.org>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../lib/pytis/data/access.py:432
msgid "Access denied"
msgstr ""

#: ../lib/pytis/data/dbapi.py:87
msgid "Waiting for server recovery"
msgstr ""

#: ../lib/pytis/data/dbapi.py:99
msgid "Can't connect to database"
msgstr ""

#: ../lib/pytis/data/dbapi.py:226
msgid "Database interface error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:245
msgid "Database connection timeout"
msgstr ""

#: ../lib/pytis/data/dbapi.py:247 ../lib/pytis/data/dbapi.py:381
msgid "Database connection error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:261
msgid "Database operational error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:268
msgid "Database internal error"
msgstr ""

#: ../lib/pytis/data/dbapi.py:272
msgid "Database integrity violation"
msgstr ""

#: ../lib/pytis/data/dbdata.py:291
msgid "Too many database connections"
msgstr ""

#: ../lib/pytis/data/dbdata.py:719
msgid "Database error"
msgstr ""

#: ../lib/pytis/data/dbdata.py:788
msgid "Invalid user name or password"
msgstr ""

#: ../lib/pytis/data/postgresql.py:453 ../lib/pytis/data/postgresql.py:563
#: ../lib/pytis/data/postgresql.py:575
msgid "Method not implemented"
msgstr ""

#: ../lib/pytis/data/postgresql.py:3558
msgid "Invalid database counter value"
msgstr ""

#: ../lib/pytis/data/types_.py:371
#, python-format
msgid "Wildcard matching not supported for values of type '%s'."
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:378
msgid "Empty value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:394
msgid "Invalid value"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:542
#, python-format
msgid "Minimal value is %(minimum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:545
#, python-format
msgid "Maximal value is %(maximum)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:585
#, python-format
msgid "Minimal size %(minlen)s not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:587
#, python-format
msgid "Maximal size %(maxlen)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:738
msgid "Lower range bound higher than the upper one"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:831
msgid "Not an integer"
msgstr ""

#: ../lib/pytis/data/types_.py:1003
msgid "Invalid number"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1136
#, python-format
msgid "Minimal length %(minlen)s characters not satisfied"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1138
#, python-format
msgid "Maximal length %(maxlen)s characters exceeded"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1264
msgid "Please use mix of letters and non-letters in your password"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1270
msgid "Enter the password twice to eliminate typos"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1273
msgid "Passwords don't match"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1296
msgid "Invalid MD5 hash"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1303 ../lib/pytis/data/types_.py:1341
#: ../lib/pytis/data/types_.py:1371 ../lib/pytis/data/types_.py:1391
#: ../lib/pytis/data/types_.py:2110
msgid "Invalid format"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1326
msgid "Invalid color format ('#RGB' or '#RRGGBB')"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1346
#, python-format
msgid "Invalid inet address mask: %(mask)s"
msgstr ""

#. User input validation error message.
#: ../lib/pytis/data/types_.py:1353
#, python-format
msgid "Invalid inet address value %(addr)s"
msgstr ""

#: ../lib/pytis/data/types_.py:1518
msgid "Invalid date or time format"
msgstr ""

#: ../lib/pytis/data/types_.py:1725
msgid "Date outside the allowed range"
msgstr ""

#: ../lib/pytis/data/types_.py:2224
msgid "Invalid boolean type input value"
msgstr ""

#: ../lib/pytis/data/types_.py:2415
msgid "Invalid graphics format"
msgstr ""

#: ../lib/pytis/data/types_.py:2473
#, python-format
msgid "Minimal pixel size %(minsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2476
#, python-format
msgid "Maximal pixel size %(maxsize)s exceeded"
msgstr ""

#: ../lib/pytis/data/types_.py:2480
#, python-format
msgid "Unsupported format %(format)s; valid formats: %(formats)s"
msgstr ""

#: ../lib/pytis/data/types_.py:2527
msgid "Invalid hierarchical value format"
msgstr ""

#: ../lib/pytis/data/types_.py:2529
msgid "One of hierarchical value items is too long"
msgstr ""

#: ../lib/pytis/data/types_.py:2531
msgid "One of hierarchical value items contains invalid characters"
msgstr ""

#: ../lib/pytis/presentation/field.py:482
msgid "Such value already exists."
msgstr ""

#: ../lib/pytis/presentation/field.py:725
msgid "unlimited"
msgstr ""

#, fuzzy
#~ msgid "Instructions"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Selections"
#~ msgstr "Műveletek"

#, fuzzy
#~ msgid "Dictation"
#~ msgstr "Műveletek"
